[package]
name = "consumer-no_std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.orxg/cargo/reference/manifest.html

[dependencies]
rustls-rustcrypto = { path = "../../" }
rustls = { workspace = true, default-features = false }